import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/lib/theme/colors";

export function createCommerceHomeStyles(c: ThemeColors) {
  return StyleSheet.create({
    safe: {
      flex: 1,
    },
    bodySafe: {
      flex: 1,
    },
    topBar: {
      position: "absolute",
      top: 0,
      right: 0,
      left: 0,
      zIndex: 2,
      paddingRight: 16,
      paddingLeft: 16,
      alignItems: "flex-end",
    },
    onlineRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      minHeight: 48,
      paddingVertical: 10,
      paddingHorizontal: 12,
      marginRight: -4,
    },
    onlineSwitchWrap: {
      minWidth: 52,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    onlineLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: c.textMuted,
    },
    onlineLabelOn: {
      color: c.accent,
    },
    body: {
      flex: 1,
      paddingHorizontal: 28,
      paddingBottom: 0,
    },
    center: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingTop: 80,
    },
    footerMeta: {
      alignSelf: "stretch",
      alignItems: "center",
      paddingBottom: 2,
    },
    footerLine: {
      fontSize: 9,
      fontWeight: "600",
      letterSpacing: 0.2,
      color: c.accent,
      textAlign: "center",
    },
    balanceBlock: {
      alignItems: "center",
      width: "100%",
    },
    balanceLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: c.textMuted,
      marginBottom: 16,
    },
    balanceCircle: {
      width: 260,
      height: 260,
      borderRadius: 130,
      backgroundColor: c.depositHighlightBackground,
      borderWidth: 2,
      borderColor: c.depositHighlightBorder,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 20,
    },
    balanceValueWrap: {
      width: "100%",
      alignItems: "center",
    },
    balanceValue: {
      fontSize: 48,
      fontWeight: "800",
      color: c.text,
      letterSpacing: -1,
      textAlign: "center",
      width: "100%",
    },
    balanceCurrency: {
      marginTop: 4,
      fontSize: 15,
      fontWeight: "700",
      color: c.accent,
    },
    recentCard: {
      marginTop: 18,
      width: "100%",
      maxWidth: 320,
      borderRadius: 14,
      backgroundColor: c.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
      paddingTop: 10,
      paddingBottom: 4,
      paddingHorizontal: 12,
      maxHeight: 148,
    },
    recentLabel: {
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 0.4,
      textTransform: "uppercase",
      color: c.textFaint,
      marginBottom: 6,
      textAlign: "center",
    },
    recentScroll: {
      maxHeight: 112,
    },
    recentScrollContent: {
      paddingBottom: 4,
    },
    recentRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 7,
    },
    recentRowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.borderLight,
    },
    recentAmount: {
      fontSize: 14,
      fontWeight: "800",
      color: c.accent,
      minWidth: 64,
    },
    recentTexts: {
      flex: 1,
      minWidth: 0,
    },
    recentName: {
      fontSize: 13,
      fontWeight: "600",
      color: c.text,
    },
    recentDate: {
      marginTop: 1,
      fontSize: 11,
      fontWeight: "600",
      color: c.textFaint,
    },
    recentDateJustNow: {
      color: c.accent,
      fontWeight: "700",
    },
    lastTxEmpty: {
      marginTop: 22,
      fontSize: 13,
      fontWeight: "600",
      color: c.textFaint,
      textAlign: "center",
    },
    flashOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 40,
      elevation: 24,
      justifyContent: "flex-end",
    },
    flashBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    flashSheet: {
      backgroundColor: c.modal,
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
      paddingHorizontal: 24,
      paddingTop: 22,
      alignItems: "center",
    },
    flashTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: c.textMuted,
      textAlign: "center",
    },
    flashAmount: {
      marginTop: 10,
      fontSize: 64,
      fontWeight: "800",
      color: c.accent,
      letterSpacing: -1.5,
      textAlign: "center",
      width: "100%",
      fontVariant: ["tabular-nums"],
    },
    flashCurrency: {
      marginTop: 2,
      marginBottom: 8,
      fontSize: 16,
      fontWeight: "700",
      color: c.accent,
      textAlign: "center",
    },
  });
}
