import type { ThemeColors } from "@/lib/theme/colors";
import { Platform, StyleSheet } from "react-native";

export function createPayHomeStyles(c: ThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: c.background,
    },
    payScreenBody: {
      flex: 1,
      flexDirection: "column",
      paddingHorizontal: 22,
      paddingBottom: 0,
    },
    payContentSpacer: {
      flex: 1,
      minHeight: 0,
    },
    payTopBlock: {
      width: "100%",
      paddingTop: 28,
    },
    payKeypadSpacer: {
      flex: 1,
      minHeight: 28,
    },
    payKeypadBlock: {
      width: "100%",
      flexShrink: 0,
    },
    payBalanceRow: {
      alignItems: "center",
      marginBottom: 2,
      paddingHorizontal: 8,
    },
    payBalanceText: {
      fontSize: 14,
      fontWeight: "600",
      color: c.textMuted,
      fontVariant: ["tabular-nums"],
    },
    topUpSuccessBanner: {
      textAlign: "center",
      fontSize: 13,
      fontWeight: "700",
      color: c.accent,
      marginBottom: 10,
      paddingHorizontal: 8,
    },
    topBarRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 0,
      marginBottom: 20,
      gap: 8,
    },
    balanceAddBtn: {
      marginLeft: 0,
      marginTop: 0,
      padding: 2,
      justifyContent: "center",
      alignItems: "center",
      flexShrink: 0,
    },
    balanceAddIcon: {
      fontSize: 22,
      fontWeight: "400",
      color: c.accent,
      lineHeight: 24,
      includeFontPadding: false,
      textAlign: "center",
    },
    balanceAddBtnPressed: {
      opacity: 0.55,
      transform: [{ scale: 0.94 }],
    },
    connexionModalRoot: {
      flex: 1,
      justifyContent: "center",
    },
    connexionModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    connexionModalCard: {
      marginHorizontal: 28,
      backgroundColor: c.modal,
      borderRadius: 16,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 16,
      zIndex: 1,
    },
    connexionModalTitle: {
      fontSize: 17,
      fontWeight: "800",
      color: c.text,
      marginBottom: 8,
    },
    connexionModalMessage: {
      fontSize: 14,
      color: c.textSecondary,
      lineHeight: 20,
    },
    connexionModalActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 18,
      paddingTop: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    connexionModalBtnHit: {
      paddingVertical: 6,
      paddingHorizontal: 4,
      minWidth: 44,
      minHeight: 36,
      justifyContent: "center",
    },
    connexionModalBtnPressed: {
      opacity: 0.65,
    },
    connexionModalBtnAnnuler: {
      fontSize: 13,
      fontWeight: "600",
      color: c.textMuted,
    },
    connexionModalBtnConnexion: {
      fontSize: 13,
      fontWeight: "700",
      color: c.accent,
    },
    /** Overlay in-tree (pas RN Modal) — autofocus clavier Android. */
    payPinOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 100,
      elevation: 24,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 28,
    },
    payPinModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    payPinCard: {
      width: "100%",
      maxWidth: 340,
      backgroundColor: c.modal,
      borderRadius: 16,
      paddingHorizontal: 22,
      paddingTop: 20,
      paddingBottom: 18,
      zIndex: 1,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
    },
    payPinFeedback: {
      marginTop: 8,
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
    },

    payPinModalTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: c.text,
      marginBottom: 12,
      textAlign: "center",
    },
    payPinModalSub: {
      fontSize: 12,
      fontWeight: "400",
      color: c.textSecondary,
      lineHeight: 17,
      marginBottom: 10,
      textAlign: "center",
    },
    payPinModalSubAmount: {
      color: c.accent,
      fontWeight: "400",
    },
    payPinModalError: {
      fontSize: 11,
      fontWeight: "600",
      color: c.destructive,
      lineHeight: 15,
      marginBottom: 10,
      textAlign: "center",
    },
    /** Zone tactile des ronds PIN (style iPhone) — pas de champ « boîte ». */
    payPinModalInput: {
      height: 56,
      marginBottom: 8,
      marginTop: 4,
      backgroundColor: "transparent",
      borderWidth: 0,
      justifyContent: "center",
      alignItems: "center",
    },
    recipientRow: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      minWidth: 0,
      marginRight: 4,
    },
    recipientRowPressed: {
      opacity: 0.72,
    },
    recipientThumb: {
      width: 52,
      height: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surfaceMuted,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    recipientThumbMuted: {
      borderColor: c.borderLight,
      opacity: 0.9,
    },
    recipientThumbImage: {
      width: 52,
      height: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      marginRight: 12,
    },
    recipientThumbLetter: {
      fontSize: 20,
      fontWeight: "800",
      color: c.accent,
    },
    recipientTexts: {
      flex: 1,
      minWidth: 0,
      justifyContent: "center",
      minHeight: 52,
      paddingTop: 0,
    },
    driverName: {
      fontSize: 13,
      fontWeight: "700",
      color: c.text,
    },
    driverPhone: {
      fontSize: 11,
      color: c.textMuted,
    },
    inputSection: {
      flexShrink: 0,
      marginBottom: 8,
    },
    inputLabel: {
      fontSize: 13,
      color: c.textMuted,
      fontWeight: "600",
      marginBottom: 6,
      letterSpacing: 0.8,
      textAlign: "center",
    },
    inputWrapper: {
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      paddingHorizontal: 18,
      paddingTop: 8,
      paddingBottom: 4,
    },
    amountRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
    },
    amountDisplayWrap: {
      minWidth: 0,
      flexShrink: 1,
      justifyContent: "center",
    },
    amountDisplay: {
      fontSize: 50,
      fontWeight: "800",
      color: c.text,
      letterSpacing: -0.5,
      fontVariant: ["tabular-nums"],
      lineHeight: 50,
      ...Platform.select({
        android: {
          textAlignVertical: "center" as const,
          includeFontPadding: false,
        },
        default: {},
      }),
    },
    currency: {
      fontSize: 19,
      fontWeight: "800",
      color: c.textFaint,
      marginLeft: 2,
    },
    payFeeLine: {
      marginTop: -10,
      fontSize: 13,
      lineHeight: 15,
      fontWeight: "600",
      color: c.textMuted,
      textAlign: "center",
      fontVariant: ["tabular-nums"],
      ...Platform.select({
        android: { includeFontPadding: false },
        default: {},
      }),
    },
    quickAmountsRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 10,
      gap: 10,
    },
    quickAmountBtn: {
      minHeight: 36,
      paddingHorizontal: 18,
      paddingVertical: 8,
      borderRadius: 18,
      backgroundColor: c.surfaceMuted,
      borderWidth: 1,
      borderColor: c.border,
      justifyContent: "center",
      alignItems: "center",
    },
    quickAmountBtnSelected: {
      backgroundColor: c.depositHighlightBackground,
      borderColor: c.accent,
    },
    quickAmountBtnPressed: {
      opacity: 0.75,
      transform: [{ scale: 0.96 }],
    },
    quickAmountBtnDisabled: {
      opacity: 0.45,
    },
    quickAmountBtnText: {
      fontSize: 14,
      fontWeight: "700",
      color: c.text,
      fontVariant: ["tabular-nums"],
    },
    quickAmountBtnTextSelected: {
      color: c.accent,
    },
    actionSection: {
      marginTop: 18,
    },
    quickAmountsRow: {
      flexDirection: "row",
      justifyContent: "center",
      flexWrap: "nowrap",
      gap: 8,
      marginTop: 10,
      paddingHorizontal: 4,
    },
    quickAmountChip: {
      flexGrow: 1,
      flexBasis: 0,
      minHeight: 40,
      paddingHorizontal: 6,
      borderRadius: 12,
      backgroundColor: "transparent",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
      alignItems: "center",
      justifyContent: "center",
    },
    quickAmountChipSelected: {
      backgroundColor: "transparent",
      borderWidth: 1,
      borderColor: c.accent,
    },
    quickAmountChipPressed: {
      opacity: 0.75,
    },
    quickAmountChipDisabled: {
      opacity: 0.45,
    },
    quickAmountChipText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.textMuted,
      fontVariant: ["tabular-nums"],
    },
    quickAmountChipTextSelected: {
      color: c.accent,
    },
    payButton: {
      backgroundColor: c.accent,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      elevation: 2,
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 3,
    },
    payButtonPressed: {
      backgroundColor: c.accentDark,
      transform: [{ scale: 0.98 }],
    },
    payButtonDisabled: {
      backgroundColor: c.disabledButton,
      elevation: 0,
    },
    payButtonText: {
      color: c.accentOn,
      fontSize: 17,
      fontWeight: "700",
      /** letterSpacing coupe souvent la dernière lettre sur Android (ex. « …maintenant »). */
      letterSpacing: 0,
      paddingHorizontal: 2,
      textAlign: "center",
    },
  });
}
