import type { ThemeColors } from "@/lib/theme/colors";
import { Platform, StyleSheet } from "react-native";

export function createPayHomeStyles(c: ThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: c.background,
    },
    payScreenBody: {
      flex: 1,
      flexDirection: "column",
      paddingHorizontal: 22,
      paddingBottom: 8,
    },
    payContentSpacer: {
      flex: 1,
      minHeight: 0,
    },
    payTopBlock: {
      width: "100%",
      paddingTop: 28,
    },
    payBottomBlock: {
      width: "100%",
      flexShrink: 0,
    },
    topBarRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 0,
      marginBottom: 20,
      gap: 8,
    },
    balanceAddBtn: {
      marginLeft: 0,
      marginTop: 0,
      padding: 2,
      justifyContent: "center",
      alignItems: "center",
      flexShrink: 0,
    },
    balanceAddIcon: {
      fontSize: 22,
      fontWeight: "400",
      color: c.accent,
      lineHeight: 24,
      includeFontPadding: false,
      textAlign: "center",
    },
    balanceAddBtnPressed: {
      opacity: 0.55,
      transform: [{ scale: 0.94 }],
    },
    connexionModalRoot: {
      flex: 1,
      justifyContent: "center",
    },
    connexionModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    connexionModalCard: {
      marginHorizontal: 28,
      backgroundColor: c.modal,
      borderRadius: 16,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 16,
      zIndex: 1,
    },
    connexionModalTitle: {
      fontSize: 17,
      fontWeight: "800",
      color: c.text,
      marginBottom: 8,
    },
    connexionModalMessage: {
      fontSize: 14,
      color: c.textSecondary,
      lineHeight: 20,
    },
    connexionModalActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 18,
      paddingTop: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    connexionModalBtnHit: {
      paddingVertical: 6,
      paddingHorizontal: 4,
      minWidth: 44,
      minHeight: 36,
      justifyContent: "center",
    },
    connexionModalBtnPressed: {
      opacity: 0.65,
    },
    connexionModalBtnAnnuler: {
      fontSize: 13,
      fontWeight: "600",
      color: c.textMuted,
    },
    connexionModalBtnConnexion: {
      fontSize: 13,
      fontWeight: "700",
      color: c.accent,
    },
    /** Overlay in-tree (pas RN Modal) — seul moyen fiable d’autofocus clavier Android. */
    payPinOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 100,
      elevation: 24,
      justifyContent: "flex-end",
    },
    payPinModalKeyboardWrap: {
      flex: 1,
      justifyContent: "flex-end",
      width: "100%",
    },
    payPinModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    payPinSheet: {
      position: "absolute",
      left: 0,
      right: 0,
      backgroundColor: c.modal,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      paddingHorizontal: 22,
      paddingTop: 10,
      zIndex: 1,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.borderLight,
      width: "100%",
    },
    /** Collé au clavier : pas d’arrondi bas (évite un « vide » visuel). */
    payPinSheetKeyboardFlush: {
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
    },
    payPinSheetHandle: {
      alignSelf: "center",
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.border,
      marginBottom: 14,
    },
    payPinFeedback: {
      marginTop: 8,
      width: "100%",
      alignItems: "center",
      justifyContent: "center",
    },

    payPinModalTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: c.text,
      marginBottom: 12,
      textAlign: "center",
    },
    payPinModalSub: {
      fontSize: 12,
      fontWeight: "600",
      color: c.textSecondary,
      lineHeight: 17,
      marginBottom: 10,
      textAlign: "center",
    },
    payPinModalError: {
      fontSize: 11,
      fontWeight: "600",
      color: c.destructive,
      lineHeight: 15,
      marginBottom: 10,
      textAlign: "center",
    },
    /** Zone tactile des ronds PIN (style iPhone) — pas de champ « boîte ». */
    payPinModalInput: {
      height: 56,
      marginBottom: 8,
      marginTop: 4,
      backgroundColor: "transparent",
      borderWidth: 0,
      justifyContent: "center",
      alignItems: "center",
    },
    recipientRow: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      minWidth: 0,
      marginRight: 4,
    },
    recipientThumb: {
      width: 52,
      height: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surfaceMuted,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    recipientThumbImage: {
      width: 52,
      height: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      marginRight: 12,
    },
    recipientThumbLetter: {
      fontSize: 20,
      fontWeight: "800",
      color: c.accent,
    },
    recipientTexts: {
      flex: 1,
      minWidth: 0,
      justifyContent: "center",
      minHeight: 52,
      paddingTop: 0,
    },
    driverName: {
      fontSize: 13,
      fontWeight: "700",
      color: c.text,
    },
    driverPhone: {
      fontSize: 11,
      color: c.textMuted,
    },
    inputSection: {
      marginBottom: 0,
    },
    inputLabel: {
      fontSize: 13,
      color: c.textMuted,
      fontWeight: "600",
      marginBottom: 10,
      letterSpacing: 0.8,
      textAlign: "center",
    },
    inputWrapper: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      paddingHorizontal: 18,
      paddingVertical: 8,
      minHeight: 96,
    },
    amountDisplayWrap: {
      minHeight: 84,
      minWidth: 0,
      flexShrink: 1,
      justifyContent: "center",
    },
    amountDisplay: {
      fontSize: 50,
      fontWeight: "800",
      color: c.text,
      letterSpacing: -0.5,
      fontVariant: ["tabular-nums"],
      ...Platform.select({
        android: { textAlignVertical: "center" as const },
        default: {},
      }),
    },
    currency: {
      fontSize: 19,
      fontWeight: "800",
      color: c.textFaint,
      marginLeft: 10,
    },
    actionSection: {
      marginTop: 18,
    },
    payButton: {
      backgroundColor: c.accent,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      elevation: 2,
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 3,
    },
    payButtonPressed: {
      backgroundColor: c.accentDark,
      transform: [{ scale: 0.98 }],
    },
    payButtonDisabled: {
      backgroundColor: c.disabledButton,
      elevation: 0,
    },
    payButtonText: {
      color: c.accentOn,
      fontSize: 17,
      fontWeight: "700",
      /** letterSpacing coupe souvent la dernière lettre sur Android (ex. « …maintenant »). */
      letterSpacing: 0,
      paddingHorizontal: 2,
      textAlign: "center",
    },
    successSafe: {
      flex: 1,
      backgroundColor: c.background,
    },
    successScroll: {
      flex: 1,
    },
    successScrollContent: {
      flexGrow: 1,
      paddingHorizontal: 24,
      paddingTop: 28,
      paddingBottom: 16,
    },
    successTop: {
      alignItems: "center",
    },
    successIconWrap: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: c.depositHighlightBackground,
      borderWidth: 1,
      borderColor: c.depositHighlightBorder,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 18,
    },
    successTitle: {
      color: c.text,
      fontSize: 26,
      fontWeight: "800",
      textAlign: "center",
    },
    successSubtitle: {
      color: c.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      textAlign: "center",
      marginTop: 8,
      marginBottom: 22,
      paddingHorizontal: 12,
    },
    successAmount: {
      color: c.accent,
      fontSize: 36,
      fontWeight: "800",
      letterSpacing: -0.5,
      textAlign: "center",
    },
    successAmountCurrency: {
      color: c.textFaint,
      fontSize: 15,
      fontWeight: "700",
      textAlign: "center",
      marginTop: 4,
      marginBottom: 28,
    },
    successReceipt: {
      width: "100%",
      backgroundColor: c.surfaceMuted,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
      paddingHorizontal: 16,
      paddingVertical: 6,
    },
    successRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      paddingVertical: 7,
      gap: 12,
    },
    successRowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.borderLight,
    },
    successRowLabel: {
      flexShrink: 0,
      fontSize: 12,
      fontWeight: "600",
      color: c.textMuted,
      paddingTop: 1,
    },
    successRowValue: {
      flex: 1,
      fontSize: 12,
      fontWeight: "700",
      color: c.text,
      textAlign: "right",
    },
    successRowValueMuted: {
      fontWeight: "600",
      color: c.textSecondary,
    },
    successStatusOk: {
      color: c.accent,
    },
    successHistoryInScroll: {
      width: "100%",
      marginTop: 20,
    },
    successActions: {
      width: "100%",
      paddingHorizontal: 24,
      paddingTop: 10,
      paddingBottom: 12,
      backgroundColor: c.background,
    },
    successPrimaryBtn: {
      backgroundColor: c.accent,
      height: 54,
      borderRadius: 27,
      alignItems: "center",
      justifyContent: "center",
    },
    successPrimaryBtnPressed: {
      opacity: 0.92,
      transform: [{ scale: 0.99 }],
    },
    successPrimaryBtnText: {
      color: c.accentOn,
      fontSize: 16,
      fontWeight: "800",
    },
    successSecondaryBtn: {
      height: 48,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: c.surface,
    },
    successSecondaryBtnPressed: {
      opacity: 0.75,
    },
    successSecondaryBtnText: {
      color: c.text,
      fontSize: 15,
      fontWeight: "700",
    },
  });
}
