import type { ThemeColors } from "@/lib/theme/colors";
import { Platform, StyleSheet } from "react-native";

export function createPayHomeStyles(c: ThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: c.background,
    },
    payScreenBody: {
      flex: 1,
      flexDirection: "column",
      paddingHorizontal: 22,
      paddingBottom: 8,
    },
    payContentSpacer: {
      flex: 1,
      minHeight: 0,
    },
    payTopBlock: {
      width: "100%",
      paddingTop: 28,
    },
    payBottomBlock: {
      width: "100%",
      flexShrink: 0,
    },
    topBarRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 0,
      marginBottom: 20,
      gap: 8,
    },
    balanceValueGroup: {
      flexDirection: "row",
      alignItems: "center",
      flexShrink: 0,
      flexWrap: "wrap",
      justifyContent: "flex-end",
    },
    balanceAmountNum: {
      fontSize: 14,
      fontWeight: "800",
      color: c.accent,
    },
    balanceCurrency: {
      fontSize: 10,
      fontWeight: "700",
      color: c.textFaint,
      marginLeft: 5,
    },
    balanceAddBtn: {
      marginLeft: 6,
      marginTop: 0,
      padding: 2,
      justifyContent: "center",
      alignItems: "center",
    },
    balanceAddBtnPressed: {
      opacity: 0.55,
      transform: [{ scale: 0.94 }],
    },
    connexionModalRoot: {
      flex: 1,
      justifyContent: "center",
    },
    connexionModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    connexionModalCard: {
      marginHorizontal: 28,
      backgroundColor: c.modal,
      borderRadius: 16,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 16,
      zIndex: 1,
    },
    connexionModalTitle: {
      fontSize: 17,
      fontWeight: "800",
      color: c.text,
      marginBottom: 8,
    },
    connexionModalMessage: {
      fontSize: 14,
      color: c.textSecondary,
      lineHeight: 20,
    },
    connexionModalActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 18,
      paddingTop: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    connexionModalBtnHit: {
      paddingVertical: 6,
      paddingHorizontal: 4,
      minWidth: 44,
      minHeight: 36,
      justifyContent: "center",
    },
    connexionModalBtnPressed: {
      opacity: 0.65,
    },
    connexionModalBtnAnnuler: {
      fontSize: 13,
      fontWeight: "600",
      color: c.textMuted,
    },
    connexionModalBtnConnexion: {
      fontSize: 13,
      fontWeight: "700",
      color: c.accent,
    },
    payPinModalKeyboardWrap: {
      flex: 1,
    },
    payPinModalRoot: {
      flex: 1,
      justifyContent: "flex-start",
    },
    payPinModalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    payPinModalCard: {
      marginHorizontal: 24,
      backgroundColor: c.modal,
      borderRadius: 20,
      padding: 22,
      zIndex: 1,
    },
    payPinModalTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: c.text,
      marginBottom: 8,
    },
    payPinModalSub: {
      fontSize: 14,
      color: c.textSecondary,
      lineHeight: 20,
      marginBottom: 10,
    },
    payPinModalError: {
      fontSize: 13,
      fontWeight: "600",
      color: c.destructive,
      lineHeight: 18,
      marginBottom: 12,
    },
    payPinModalInput: {
      height: 52,
      fontSize: 22,
      fontWeight: "700",
      letterSpacing: 8,
      textAlign: "center",
      color: c.text,
      backgroundColor: c.inputBackground,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.border,
      marginBottom: 20,
      ...Platform.select({
        android: {
          includeFontPadding: false,
          textAlignVertical: "center",
        },
        default: {},
      }),
    },
    payPinModalInputError: {
      borderColor: c.inputErrorBorder,
      backgroundColor: c.inputErrorBackground,
    },
    payPinModalActions: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      gap: 12,
    },
    payPinModalCancelBtn: {
      paddingVertical: 14,
      paddingHorizontal: 16,
    },
    payPinModalCancelText: {
      fontSize: 16,
      fontWeight: "600",
      color: c.textSecondary,
    },
    payPinModalOkBtn: {
      flex: 1,
      backgroundColor: c.accent,
      paddingVertical: 14,
      borderRadius: 24,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 48,
    },
    payPinModalOkBtnDisabled: {
      backgroundColor: c.disabledButton,
    },
    payPinModalOkBtnPressed: {
      opacity: 0.92,
    },
    payPinModalOkText: {
      color: c.accentOn,
      fontSize: 16,
      fontWeight: "800",
    },
    recipientRow: {
      flexDirection: "row",
      alignItems: "center",
      flex: 1,
      minWidth: 0,
      marginRight: 4,
    },
    recipientThumb: {
      width: 52,
      height: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surfaceMuted,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    recipientThumbImage: {
      width: 52,
      height: 52,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      marginRight: 12,
    },
    recipientThumbLetter: {
      fontSize: 20,
      fontWeight: "800",
      color: c.accent,
    },
    recipientTexts: {
      flex: 1,
      minWidth: 0,
      justifyContent: "center",
      minHeight: 52,
      paddingTop: 0,
    },
    driverName: {
      fontSize: 13,
      fontWeight: "700",
      color: c.text,
    },
    driverPhone: {
      fontSize: 11,
      color: c.textMuted,
    },
    inputSection: {
      marginBottom: 0,
    },
    inputLabel: {
      fontSize: 13,
      color: c.textMuted,
      fontWeight: "600",
      marginBottom: 10,
      letterSpacing: 0.8,
      textAlign: "center",
    },
    inputWrapper: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
      paddingHorizontal: 18,
      paddingVertical: 8,
      minHeight: 96,
    },
    amountDisplayWrap: {
      minHeight: 84,
      minWidth: 0,
      flexShrink: 1,
      justifyContent: "center",
    },
    amountDisplay: {
      fontSize: 50,
      fontWeight: "800",
      color: c.text,
      letterSpacing: -0.5,
      fontVariant: ["tabular-nums"],
      ...Platform.select({
        android: { textAlignVertical: "center" as const },
        default: {},
      }),
    },
    currency: {
      fontSize: 19,
      fontWeight: "800",
      color: c.textFaint,
      marginLeft: 10,
    },
    actionSection: {
      marginTop: 18,
    },
    payButton: {
      backgroundColor: c.accent,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      elevation: 2,
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.08,
      shadowRadius: 3,
    },
    payButtonPressed: {
      backgroundColor: c.accentDark,
      transform: [{ scale: 0.98 }],
    },
    payButtonDisabled: {
      backgroundColor: c.disabledButton,
      elevation: 0,
    },
    payButtonText: {
      color: c.accentOn,
      fontSize: 17,
      fontWeight: "bold",
      letterSpacing: 0.2,
    },
    successContainer: {
      flex: 1,
      backgroundColor: c.accent,
      justifyContent: "center",
      alignItems: "center",
      padding: 18,
    },
    successEmoji: { fontSize: 76 },
    successText: {
      color: c.textInverse,
      fontSize: 32,
      fontWeight: "900",
      marginTop: 8,
    },
    successSub: {
      color: c.textInverse,
      fontSize: 14,
      opacity: 0.9,
      marginTop: 8,
      textAlign: "center",
    },
    resetButton: {
      marginTop: 44,
      paddingVertical: 12,
      paddingHorizontal: 18,
      backgroundColor: "rgba(255,255,255,0.2)",
      borderRadius: 16,
    },
    resetButtonText: {
      color: c.textInverse,
      fontSize: 14,
      fontWeight: "bold",
    },
  });
}
