import type { ThemeColors } from "@/lib/theme/colors";
import { StyleSheet } from "react-native";

export function createPayOutcomeSheetStyles(c: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 110,
      elevation: 28,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 28,
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    card: {
      width: "100%",
      maxWidth: 340,
      backgroundColor: c.modal,
      borderRadius: 16,
      paddingHorizontal: 22,
      paddingTop: 20,
      paddingBottom: 18,
      zIndex: 1,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
    },
    iconWrap: {
      alignSelf: "center",
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: c.depositHighlightBackground,
      borderWidth: 1,
      borderColor: c.depositHighlightBorder,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 12,
    },
    title: {
      fontSize: 18,
      fontWeight: "800",
      color: c.text,
      textAlign: "center",
    },
    titleError: {
      fontSize: 17,
      fontWeight: "800",
      color: c.destructive,
      textAlign: "center",
    },
    amount: {
      marginTop: 8,
      fontSize: 28,
      fontWeight: "800",
      color: c.accent,
      textAlign: "center",
      fontVariant: ["tabular-nums"],
    },
    recipientBlock: {
      marginTop: 14,
      marginBottom: 16,
      paddingHorizontal: 4,
      alignItems: "center",
    },
    recipientLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: c.textMuted,
      textAlign: "center",
      letterSpacing: 0.4,
      textTransform: "uppercase",
      marginBottom: 6,
    },
    recipientName: {
      fontSize: 26,
      fontWeight: "800",
      color: c.text,
      textAlign: "center",
      lineHeight: 32,
      letterSpacing: -0.3,
    },
    message: {
      marginTop: 8,
      marginBottom: 16,
      fontSize: 14,
      fontWeight: "500",
      color: c.textSecondary,
      textAlign: "center",
      lineHeight: 20,
      paddingHorizontal: 4,
    },
    okBtn: {
      alignSelf: "center",
      backgroundColor: c.accent,
      minWidth: 120,
      height: 40,
      paddingHorizontal: 28,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
    },
    okBtnPressed: {
      opacity: 0.92,
      transform: [{ scale: 0.99 }],
    },
    okBtnText: {
      color: c.accentOn,
      fontSize: 13,
      fontWeight: "700",
    },
  });
}
