import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/lib/theme/colors";

export function createProfileStyles(c: ThemeColors) {
  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: c.background,
    },
    loadingWrap: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    scroll: {
      paddingBottom: 36,
      paddingHorizontal: 20,
    },
    header: {
      paddingTop: 12,
      paddingBottom: 8,
    },
    title: {
      fontSize: 26,
      fontWeight: "800",
      color: c.text,
      letterSpacing: -0.3,
    },
    subtitle: {
      marginTop: 4,
      fontSize: 13,
      fontWeight: "600",
      color: c.textMuted,
    },
    hero: {
      alignItems: "center",
      paddingTop: 18,
      paddingBottom: 20,
    },
    avatar: {
      width: 84,
      height: 84,
      borderRadius: 42,
      backgroundColor: c.depositHighlightBackground,
      borderWidth: 1,
      borderColor: c.depositHighlightBorder,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 12,
    },
    avatarText: {
      fontSize: 28,
      fontWeight: "800",
      color: c.accent,
    },
    name: {
      fontSize: 22,
      fontWeight: "800",
      color: c.text,
      textAlign: "center",
    },
    statusChip: {
      marginTop: 10,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: c.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
    },
    statusChipOk: {
      backgroundColor: c.depositHighlightBackground,
      borderColor: c.depositHighlightBorder,
    },
    statusChipWarn: {
      backgroundColor: c.destructiveSoft,
      borderColor: c.destructiveBorder,
    },
    statusChipText: {
      fontSize: 12,
      fontWeight: "700",
      color: c.textSecondary,
    },
    statusChipTextOk: {
      color: c.accent,
    },
    statusChipTextWarn: {
      color: c.destructive,
    },
    balanceCard: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
      paddingHorizontal: 16,
      paddingVertical: 16,
      marginBottom: 14,
    },
    balanceLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: c.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    balanceRow: {
      marginTop: 6,
      flexDirection: "row",
      alignItems: "flex-end",
      justifyContent: "space-between",
      gap: 12,
    },
    balanceValue: {
      flex: 1,
      fontSize: 28,
      fontWeight: "800",
      color: c.accent,
      letterSpacing: -0.4,
    },
    balanceCurrency: {
      fontSize: 13,
      fontWeight: "700",
      color: c.textFaint,
      marginBottom: 4,
    },
    sectionCard: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
      paddingHorizontal: 14,
      paddingTop: 6,
      paddingBottom: 10,
      marginBottom: 14,
      overflow: "hidden",
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: "800",
      color: c.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 10,
      marginTop: 4,
      paddingHorizontal: 2,
    },
    row: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
      paddingVertical: 12,
    },
    rowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.borderLight,
    },
    rowLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: c.textMuted,
      paddingTop: 1,
    },
    rowValue: {
      flex: 1,
      fontSize: 14,
      fontWeight: "700",
      color: c.text,
      textAlign: "right",
      lineHeight: 20,
    },
    rowValueMuted: {
      fontWeight: "600",
      color: c.textSecondary,
    },
    rowValueSoft: {
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 17,
    },
    rowValueMono: {
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    actionsRow: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 18,
    },
    actionBtn: {
      flex: 1,
      minWidth: 0,
      backgroundColor: c.surfaceMuted,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.borderLight,
      paddingVertical: 14,
      paddingHorizontal: 6,
      alignItems: "center",
      gap: 8,
    },
    actionBtnPressed: {
      opacity: 0.85,
    },
    actionIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.depositHighlightBackground,
      borderWidth: 1,
      borderColor: c.depositHighlightBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    actionLabel: {
      width: "100%",
      fontSize: 11,
      fontWeight: "700",
      color: c.text,
      textAlign: "center",
    },
    onboardingBanner: {
      backgroundColor: c.destructiveSoft,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.destructiveBorder,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 14,
    },
    onboardingBannerText: {
      fontSize: 13,
      fontWeight: "600",
      color: c.destructive,
      lineHeight: 18,
    },
    signOutBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      paddingVertical: 16,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.signOutBorder,
      backgroundColor: c.signOutBackground,
    },
    signOutBtnPressed: {
      opacity: 0.85,
    },
    signOutBtnDisabled: {
      opacity: 0.6,
    },
    signOutText: {
      fontSize: 13,
      fontWeight: "700",
      color: c.destructive,
    },
    appMeta: {
      marginTop: 18,
      alignItems: "center",
      gap: 4,
    },
    appMetaText: {
      fontSize: 11,
      fontWeight: "600",
      color: c.textFaint,
    },
  });
}
